stages:
  - build
  - deploy

build project:
  image: maven:maven:3.6.3-jdk-11
  stage: build
  script: "mvn install -B"
  artifacts:
    paths:
      - target/*.jar


deploy project:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - heroes
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r target/*.jar ~/api-deployment
    - sudo service project restart


